steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--dockerfile', 'dkr/build', '--destination=gcr.io/$PROJECT_ID/image', '--cache=true', '--cache-ttl=336h']
  timeout: 300s
  id: 'build'

- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--dockerfile', 'dkr/unittests', '--destination=gcr.io/$PROJECT_ID/image', '--cache=true', '--cache-ttl=336h']
  timeout: 300s
  id: 'unittests'

- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--dockerfile', 'dkr/integration', '--destination=gcr.io/$PROJECT_ID/image', '--cache=true', '--cache-ttl=336h']
  timeout: 300s
  id: 'integration'

- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--dockerfile', 'dkr/community', '--destination=gcr.io/$PROJECT_ID/image', '--cache=true', '--cache-ttl=336h']
  timeout: 300s
  id: 'community'

artifacts:
  objects:
    location: 'gs://fury-releases/$SHORT_SHA/'
    paths: ['/fury.sh']

options:
  machineType: 'N1_HIGHCPU_8'

timeout: 1200s
