steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--file', 'dkr/build', '--tag', 'fury', '.']
  timeout: 300s
  id: 'build'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--file', 'dkr/unittests', '.']
  timeout: 300s
  id: 'unittests'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--file', 'dkr/integration', '.']
  timeout: 300s
  id: 'integration'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--file', 'dkr/community', '.']
  timeout: 600s
  id: 'community'

artifacts:
  objects:
    location: 'gs://fury-releases/$SHORT_SHA/'
    paths: ['/fury.sh']

options:
  machineType: 'N1_HIGHCPU_8'

timeout: 1200s
